# Repository permission needs `Read and write permissions` setting selected under `Workflow permissions` to allow to update/create new tag

name: CI
on:
  push: # test + build + release
    branches: [ master ]
  pull_request: # test + build
    branches: [ master ]
  release: # test + build + release
    types: [ published ]
env:
  DC: ldc-1.30.0

defaults:
  run:
    shell: bash

jobs:
  build_vanilla_d:
    name: Build vanilla D
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build: [debug-fast, release-fast]
        config: [nih-cli, nih-static, nih-shared, vbe-static, vbe-shared]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ env.DC }}
      - name: Build
        run: |
          ./build/setup.sh
          ./build/builder --action=pack --remove-build --build=${{matrix.build}} --config=${{matrix.config}} --compiler=ldc2 --print-commands --print-callees --pretty --color
  build_no_deps:
    name: Build no deps
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build: [debug-fast, release-fast]
        config: [nih-cli, nih-static, nih-shared, vbe-static, vbe-shared]
        include:
          - os: ubuntu-latest
            config: nih-cli
            no_deps:
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ env.DC }}
      - name: Build
        run: |
          ./build/setup.sh
          ./build/builder --action=pack --remove-build --no-deps --build=${{matrix.build}} --config=${{matrix.config}} --compiler=ldc2 --print-commands --print-callees --pretty --color --color
      - uses: actions/upload-artifact@v3
        with:
          path: bin/
  build_wasm:
    name: Build WASM
    strategy:
      matrix:
        include:
          - target: wasm32
            config: nih-cli,nih-shared,vbe-shared
          - target: wasm32-wasi
            config: nih-cli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ env.DC }}
      - name: Build
        run: |
          ./build/setup.sh
          ./build/builder --action=pack --remove-build --no-deps --build=release-fast --target=${{matrix.target}} --config=${{matrix.config}} --compiler=ldc2 --print-commands --print-callees --pretty --color
      - uses: actions/upload-artifact@v3
        with:
          path: bin/
  test:
    name: Test suite
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            config: nih-cli
            no_deps:
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ env.DC }}
      - name: Test
        run: |
          ./build/setup.sh
          ./build/builder --action=run --remove-build --no-deps --build=debug --config=testsuite --compiler=ldc2 --print-commands --print-callees --pretty --color
  upload:
    name: Upload build
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    needs: [build_no_deps, build_wasm]
    steps:
      # Cloning is needed for `gh release create` to work. It looks repository up in .git folder
      - uses: actions/checkout@v3
      # Download build artifacts of other jobs
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: bin/
      # Update tag, so that we get proper date and commit on github
      - name: Update CI tag
        uses: richardsimko/update-tag@master
        if: github.ref == 'refs/heads/master'
        with:
          tag_name: CI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Create CI release and upload builds
      - name: Upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ls -R
          tag=`basename ${{ github.ref }}`
          if [ $tag = 'master' ]; then
            tag='CI'
          fi
          
          # --clobber Overwrite existing assets of the same name
          gh release upload $tag bin/*.zip --clobber
